### ISSUE TITLE
Weekly Alpha & Airdrop curation

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#102]
**Educational material regarding alpha & airdrops in the NEAR ecosystem**

Objective: Having NEARWEEK tease as early as possible. Best case: before things are even live. **Always ensure quality and credibility**

- [x] [NOTION ALPHA SHEET](https://lilac-sedum-c3d.notion.site/997e8dffa8804160a02e43d8e55c5294?v=5a0b62ab6b1a46dea0157deb79abdb79)
- [x] [Which media publication we can push news to.](https://docs.google.com/spreadsheets/d/1_KZmA0sl32-8dsBlyxtDTIb_O76niRsHOutjwXMSag)

- [x] [Newsletter: weekly input (quality comes first)](https://lilac-sedum-c3d.notion.site/689f267c0edb445bbed99a174afa595e?v=ab1d685cbf834237a132c14e1bcab1a4&pvs=4) 

- Monthly / biweekly twitter space for alpha dropping (where community can do alpha sharing)
- Monthly / biweekly video format / demo video

**Content areas**
- Project launches
- New product features
- Token launches 
- Airdrop campaigns

**Comment by aescobar00** [comment]
19th March 2024

1. Updated the alpha sheet base on timeline 
2. Added KOL and media list for wider amplification ( paid or non paid )

**Comment by aescobar00** [comment]
@P3ter-NEARWEEK added new alpha that can be push out and hopefully can gather the prev week alpha as well since it's still relevant

**Comment by aescobar00** [comment]
https://docs.google.com/document/d/1FmZBazFKNUQQ8DyLKM8pai9qlxIFKkjrW4-w-s27OrY/edit?usp=sharing alpha list to be posted on 5th April 2024

**Comment by b4ltasar** [comment]
This work is recurring every week to produce weekly alpha thread will archive from project
