### ISSUE TITLE
[REDACTED] Clarify direction and content in Magazine & Merchandise

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#148]
- [x] Comments on progress so far on magazine
- [x] What kind of merchandise? How many different styles? Quantity?

**Comment by b4ltasar** [comment]
**CLOTHING**

S/S:
- for giveaways
- 1 design only
- Quantity: 100 max

L/S:
- For the team 
- Exclusive design
- Quantity 15

**ACCESSORY/GIMMICK**
- Lighter

**Comment by b4ltasar** [comment]
**MAGAZINE**
- AI x NEAR Onepager commercial

- Community content interview with 5 questions for the same 4 prominent voices:

**Comment by P3ter-NEARWEEK** [comment]
Opening editorial from Illia confirmed.

@b4ltasar please coordinate with Mally in (Illia office)NEARweek TG group
