### ISSUE TITLE
TG NEAR MASTER AMPLIFICATION GROUP

### ISSUE THREAD

**Issue by b4ltasar** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#154]
We want to grow and make the private amplification group influential with KOLs and ecosystem projects 

To achieve that we need it to be a true value add 
- be able to drop real alpha to make people in the group feel special 
- make the group a network / community
- requires an engaged group owner / "community" manager --> ideally me and Marcus (if he has the time / interest), or just NW (Peter + Aescobar)

**Comment by P3ter-NEARWEEK** [comment]
**Status update**

NF PRESS RELEASE
- Getting clarification from Rob how / if we can drop embargo press releases in the TG Group such as the upcoming [Libre](https://docs.google.com/document/d/1w7GLGW7BKY_VvUgXCOKnR1akHAEc7hGssUjgOJCFIOE/edit?usp=sharing) and [TruStake](https://docs.google.com/document/d/1DRhAHA-aHnHFrZHyifXaD_TPvETVvK0eFZ7vqnO7atQ/edit?usp=sharing) announcements.

FRONTIER
- Getting clarification from Marcus how Frontier is working with embargo announcements and KOLs? do they already have such a group where you drip alpha, do you work 1:1 in DMs or is this a Growgami job?
- would you be able to invite the KOLs you work with to the group once "real" alpha is posted in the group? --> this would ofc require a format like the one sent from Rob with clear CTAs

**Comment by b4ltasar** [comment]
- [ ] Define one-pager for recurring outputs/announcements from NW, wording, format etc.

**Comment by Kisgus** [comment]
GREAT JOB!!!!!
