### ISSUE TITLE
LAUNCHING SERACLE TOKEN ON NEAR

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [NEARWEEK/NEARWEEK-COMMUNITY-CONTENT#45]
**CONFIRMED NW DELIVERABLES** 
- [x] Social Media support
- [ ] Blogpost
- [x] Twitterspace
- [x] Include in newsletter

**Comment by b4ltasar** [comment]
**CONTEXT**

Seracles latest announcement for NEAR node launch + private sale/liquid staking. 
- The NF marketing team is able to support on amplifying the node launch but Seracle would love NEARWEEK's support on the rest.
- NW to cover the news + amplification,
- TW space is wanted as well

[HERE](https://docsend.com/view/73dxkxk2gy72cuhc) is their pitch deck for additional context

Three primary comms (Seracle already listed RPC provider on NEAR https://docs.near.org/api/rpc/providers)

1. NEAR Node Launch on Oracle by Seracle: Seracle announces the successful launch of the NEAR node on Oracle, enhancing accessibility and integration capabilities.  Reference: [https://solana.com/news/solana-blockchain-node-development-blueprints-available-on-aws ](https://solana.com/news/solana-blockchain-node-development-blueprints-available-on-aws)
2. Private Sale of Seracle Token and NEAR RPC/API Access: Seracle initiates a private sale of its token on Seracle.com, providing participants with exclusive access to NEAR RPC and APIs, along with integration capabilities with other blockchain networks using the Seracle token. Reference: https://docs.seracle.com/near/experimental/experimental-changes-all-account-changes
3. Seracle Token as Liquid Staking on NEAR:: Seracle introduces the concept of liquid staking for the Seracle token on the NEAR liquidity platform, drawing parallels to the Jito token on Solana. Reference: https://medium.com/stakingbits/jito-announces-jto-airdrop-to-solana-defi-users-f0a4b2160cd7

**Comment by b4ltasar** [comment]
Still need clarification on how to support.

**Comment by P3ter-NEARWEEK** [comment]
Currently blocked, awaiting input from Oracle
